# Font settings
font_family      Liberation Mono
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size        12.0

# Colors
# Green text
foreground #00FF00
# Black background
background #000000

# Transparency
background_opacity 0.9

# Default window size (columns x rows)
initial_window_width  114c
initial_window_height 27c

# Key mappings
map f11 toggle_fullscreen
map ctrl+c copy_to_clipboard
map ctrl+v paste_from_clipboard


window_border_width 0

remember_window_size no

enable_audio_bell no
dynamic_background_opacity yes

# Set default window size
initial_window_width 1000
initial_window_height 1000

